/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package com.alibaba.himarket.dto.params.chat;

import com.alibaba.himarket.dto.converter.InputConverter;
import com.alibaba.himarket.entity.Chat;
import com.alibaba.himarket.support.chat.attachment.ChatAttachmentConfig;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

import java.util.List;

@Data
public class CreateChatParam implements InputConverter<Chat> {

    /**
     * Session ID
     */
    @NotBlank(message = "SessionId cannot be empty")
    private String sessionId;

    /**
     * Conversation ID
     */
    @NotBlank(message = "ConversationId cannot be empty")
    private String conversationId;

    /**
     * Question ID, generated by the client
     */
    @NotBlank(message = "QuestionId cannot be empty")
    private String questionId;

    /**
     * Answer ID, generated by server
     */
    private String answerId;

    /**
     * Product ID, must be the same as the product ID used to create the session
     */
    @NotBlank(message = "ProductId cannot be empty")
    private String productId;

    /**
     * Question
     */
    @NotBlank(message = "Question cannot be empty")
    private String question;

    /**
     * Multi-modal content
     */
    private List<ChatAttachmentConfig> attachments;

    /**
     * MCP servers to use in chat
     */
    private List<String> mcpProducts;

    /**
     * Skills to use in chat
     */
    private List<String> skills;

    /**
     * If need stream
     */
    private Boolean stream = true;

    /**
     * If need memory
     */
    private Boolean needMemory = true;

    private Boolean enableWebSearch = false;

    private String searchType = "";
}
